# Generated by Django 3.1.2 on 2020-11-15 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('students', '0002_auto_20201115_1916'), ('students', '0003_remove_student_marks'), ('students', '0004_student_marks'), ('students', '0005_auto_20201115_1932'), ('students', '0006_auto_20201115_1941'), ('students', '0007_auto_20201115_1944'), ('students', '0008_auto_20201115_1945')]

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AddField(
            model_name='student',
            name='absences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='student',
            name='black_marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
